trainer:
  num_epochs: 200
  batch_size: 64
  resume: True
  lr: 0.0001
  num_workers: 8
  dataset_path: /home/liyunhao/workplace/remote-datasets/cv/cls/herbarium-2022-fgvc9/
model:
  save_name: swin.pth
  num_classes: 15505
