trainer:
  num_epochs: 200
  warmup: 5
  batch_size: 64
  optimizer: adamw
  weight_decay: 0.05
  lr: 0.0001
  resume: True
  num_workers: 8
  save_dir: output
  dataset_path: /dataset/cv/cls/herbarium-2022-fgvc9/
model:
  num_classes: 15505
  genus: 2585
  institution: 60
